name: Dataflow Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, synchronize, labeled ]


jobs:
  test-dataflow:
    name: test-dataflow-py${{ matrix.python-version }}
    # run on:
    #  - all pushes to main
    #  - a PR was just labeled 'test-dataflow'
    #  - a PR with 'test-dataflow' label was opened, reopened, or synchronized
    if: |
      github.event_name == 'push' ||
      github.event.label.name == 'test-dataflow' ||
      contains( github.event.pull_request.labels.*.name, 'test-dataflow')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}'
    - name: Install deploy-time dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r worker-requirements.txt
        python -m pip install apache-beam[gcp] "git+https://github.com/TomNicholas/xarray@array_API_astype"
        python -m pip install --no-deps "git+https://github.com/xarray-contrib/cubed-xarray"
    - name: 'Run Dataflow Integration Test'
      run: |
        WORK_DIR="gs://hero-calc/work-dir/" \
        JOB_NAME="cubed-vorticity-workflow-run-${{ github.run_id }}-${{ github.run_attempt }}" \
        PROJECT=pangeo-forge-4967 \
        REGION=us-central1 \
        TEMP_LOCATION="gs://hero-calc/temp" \
        STAGING_LOCATION="gs://hero-calc/staging" \
        SERVICE_ACCOUNT_EMAIL="tom-nicholas-distributed@pangeo-forge-4967.iam.gserviceaccount.com" \
        python vorticity.py
